name: VM

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  CARGO_TERM_COLOR: 'always'
  NGINX_SOURCE_DIR: nginx
  BUILDREQUIRES_FREEBSD: >-
    git-lite
    go
    llvm19-lite
    p5-Digest-SHA
    p5-IO-Socket-INET6
    p5-IO-Socket-SSL
    p5-JSON-PP
    p5-TimeDate
    pcre2
    pkgconf
    rust
  BUILDREQUIRES_NETBSD: >-
    clang
    git-base
    go124
    p5-IO-Socket-INET6
    p5-IO-Socket-SSL
    p5-TimeDate
    pcre2
    pkgconf
    rust

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: freebsd
            version: '14.3'
          - name: netbsd
            version: '10.1'
        nginx-ref:
          - stable-1.28
        build:
          - debug

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ matrix.nginx-ref }}
          repository: 'nginx/nginx'
          path: 'nginx'
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: 'nginx/nginx-tests'
          path: 'nginx/tests'

      - name: nproc
        run: |
          NPROC=$(getconf _NPROCESSORS_ONLN)
          echo NPROC="$NPROC" >> "$GITHUB_ENV"

      - uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: |
            bin/pebble
            nginx/objs/**/CACHEDIR.TAG
            nginx/objs/**/ngx-debug
            nginx/objs/**/ngx-release
            target/
          key: ${{ matrix.os.name }}-${{ matrix.os.version }}-nginx-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ matrix.os.name }}-${{ matrix.os.version }}-nginx-

      - name: Install prerequisites (FreeBSD)
        uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # v0.32.0
        if: matrix.os.name == 'freebsd'
        with:
          environment_variables: 'CARGO_TERM_COLOR NGINX_SOURCE_DIR'
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          cpu_count: ${{ env.NPROC }}
          shutdown_vm: false
          run: |
            sudo pkg install -y ${{ env.BUILDREQUIRES_FREEBSD }}
            perl build/get-pebble.pl

      - name: Install prerequisites (NetBSD)
        uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # v0.32.0
        if: matrix.os.name == 'netbsd'
        with:
          environment_variables: 'CARGO_TERM_COLOR NGINX_SOURCE_DIR'
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          cpu_count: ${{ env.NPROC }}
          shutdown_vm: false
          run: |
            sudo pkgin -y install ${{ env.BUILDREQUIRES_NETBSD }}
            GO=go124 perl build/get-pebble.pl

      - name: build
        uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # v0.32.0
        with:
          environment_variables: 'CARGO_TERM_COLOR NGINX_SOURCE_DIR'
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          cpu_count: ${{ env.NPROC }}
          shutdown_vm: false
          run: make BUILD=${{ matrix.build }} -j ${{ env.NPROC }} build

      - name: check
        uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # v0.32.0
        with:
          environment_variables: 'CARGO_TERM_COLOR NGINX_SOURCE_DIR'
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          cpu_count: ${{ env.NPROC }}
          shutdown_vm: false
          run: make BUILD=${{ matrix.build }} check

      - name: run tests
        uses: cross-platform-actions/action@492b0c80085400348c599edace11141a4ee73524 # v0.32.0
        with:
          environment_variables: 'CARGO_TERM_COLOR NGINX_SOURCE_DIR'
          operating_system: ${{ matrix.os.name }}
          version: ${{ matrix.os.version }}
          cpu_count: ${{ env.NPROC }}
          run: |
            TEST_NGINX_PEBBLE_BINARY=$(perl build/get-pebble.pl)
            export TEST_NGINX_PEBBLE_BINARY
            make BUILD=${{ matrix.build }} TEST_PREREQ= test
